export const currencyByRupee: Currency[] = [
    {
      name: 'DOLLAR',
      value: 0.012271428,
      flag: '🇺🇸',
      symbol: '$',
    },
    {
      name: 'EURO',
      value: 0.01125809,
      flag: '🇪🇺',
      symbol: '€',
    },
    {
      name: 'POUND',
      value: 0.0099194378,
      flag: '🇬🇧',
      symbol: '£',
    },
    {
      name: 'RUBEL',
      value: 0.85040469,
      flag: '🇷🇺',
      symbol: '₽',
    },
    {
      name: 'AUS DOLLAR',
      value: 0.01732574,
      flag: '🇦🇺',
      symbol: 'A$',
    },
    {
      name: 'CAN DOLLAR',
      value: 0.016457908,
      flag: '🇨🇦',
      symbol: 'C$',
    },
    {
      name: 'YEN',
      value: 1.5909089,
      flag: '🇯🇵',
      symbol: '¥',
    },
    {
      name: 'DINAR',
      value: 0.0037446993,
      flag: '🇰🇼',
      symbol: 'KD',
    },
    {
      name: 'BITCOIN',
      value: 0.000000543544886,
      flag: '🎰',
      symbol: '₿',
    },
    {
        name: 'SWISS FRANC',
        value: 0.011836943,
        flag: '🇨🇭',
        symbol: 'CHF',
      },
      {
        name: 'SWEDISH KRONA',
        value: 0.11645675,
        flag: '🇸🇪',
        symbol: 'SEK',
      },
      {
        name: 'SINGAPORE DOLLAR',
        value: 0.01656723,
        flag: '🇸🇬',
        symbol: 'S$',
      },
      {
        name: 'NORWEGIAN KRONE',
        value: 0.11645675,
        flag: '🇳🇴',
        symbol: 'NOK',
      },
      {
        name: 'NEW ZEALAND DOLLAR',
        value: 0.01856723,
        flag: '🇳🇿',
        symbol: 'NZ$',
      },
      {
        name: 'BRAZILIAN REAL',
        value: 0.0654321,
        flag: '🇧🇷',
        symbol: 'R$',
      },
      {
        name: 'SOUTH AFRICAN RAND',
        value: 0.193764,
        flag: '🇿🇦',
        symbol: 'R',
      },
      {
        name: 'MEXICAN PESO',
        value: 0.245679,
        flag: '🇲🇽',
        symbol: 'MXN$',
      },
      {
        name: 'THAI BAHT',
        value: 0.357802,
        flag: '🇹🇭',
        symbol: '฿',
      },
      {
        name: 'CHINESE YUAN',
        value: 0.079123,
        flag: '🇨🇳',
        symbol: '¥',
      },
      {
        name: 'SOUTH KOREAN WON',
        value: 14.567,
        flag: '🇰🇷',
        symbol: '₩',
      },
      {
        name: 'TURKISH LIRA',
        value: 0.102345,
        flag: '🇹🇷',
        symbol: '₺',
      },
      {
        name: 'SRI LANKAN RUPEE',
        value: 2.345,
        flag: '🇱🇰',
        symbol: 'Rs',
      },
      {
        name: 'MALAYSIAN RINGGIT',
        value: 0.048765,
        flag: '🇲🇾',
        symbol: 'RM',
      },
      {
        name: 'SWISS FRANC',
        value: 0.011836943,
        flag: '🇨🇭',
        symbol: 'CHF',
      },
      {
        name: 'SWEDISH KRONA',
        value: 0.11645675,
        flag: '🇸🇪',
        symbol: 'SEK',
      },
      {
        name: 'SINGAPORE DOLLAR',
        value: 0.01656723,
        flag: '🇸🇬',
        symbol: 'S$',
      },
      {
        name: 'NORWEGIAN KRONE',
        value: 0.11645675,
        flag: '🇳🇴',
        symbol: 'NOK',
      },
      {
        name: 'NEW ZEALAND DOLLAR',
        value: 0.01856723,
        flag: '🇳🇿',
        symbol: 'NZ$',
      },
      {
        name: 'EGYPTIAN POUND',
        value: 0.195678,
        flag: '🇪🇬',
        symbol: 'EGP',
      },
      {
        name: 'SAUDI RIYAL',
        value: 0.046723,
        flag: '🇸🇦',
        symbol: '﷼',
      },
      {
        name: 'UAE DIRHAM',
        value: 0.045678,
        flag: '🇦🇪',
        symbol: 'د.إ',
      },
      {
        name: 'ARGENTINE PESO',
        value: 1.234567,
        flag: '🇦🇷',
        symbol: 'ARS$',
      },
      {
        name: 'HONG KONG DOLLAR',
        value: 0.095678,
        flag: '🇭🇰',
        symbol: 'HK$',
      },
      {
        name: 'TAIWAN DOLLAR',
        value: 0.356723,
        flag: '🇹🇼',
        symbol: 'NT$',
      },
      {
        name: 'INDONESIAN RUPIAH',
        value: 177.345,
        flag: '🇮🇩',
        symbol: 'Rp',
      },
      {
        name: 'PHILIPPINE PESO',
        value: 0.632456,
        flag: '🇵🇭',
        symbol: '₱',
      },
      {
        name: 'VIETNAMESE DONG',
        value: 281.567,
        flag: '🇻🇳',
        symbol: '₫',
      },
      {
        name: 'IRAQI DINAR',
        value: 17.456,
        flag: '🇮🇶',
        symbol: 'ع.د',
      },
  ];
  